workspace:
  base: /go
  path: src/github.com/keymetrics/pm2-io-apm-go

pipeline:
  tests:
    image: golang:latest
    secrets: [ codecov_token ]
    commands:
      - go get -t -v
      - go get gopkg.in/h2non/gock.v1
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - go test -v -coverprofile=c.out -covermode=atomic $(go list ./...)
      - ./cc-test-reporter after-build --exit-code 0 || echo “Skipping CC coverage upload” or upload-coverage || echo “Skipping CC coverage upload”
      - go build

  slack:
    image: plugins/slack
    channel: ci
    when:
      status: [ success, failure ]
    template: |
      {{#success build.status}}
        pm2-io-apm-go {{ build.commit }} on {{ build.branch }} succeeded @{{ build.author }}
      {{else}}
        pm2-io-apm-go build {{ build.number }} on {{ build.branch }} failed @{{ build.author }}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]